version: 2
updates:
- package-ecosystem: pip
  directory: "/auctioning_platform"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - Enforcer
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.2
    - 1.4.3
    - 1.4.5
    - 1.4.7
    - 1.4.9
  - dependency-name: pip-tools
    versions:
    - 6.0.1
  - dependency-name: marshmallow-dataclass
    versions:
    - 8.3.2
  - dependency-name: marshmallow
    versions:
    - 3.11.0
  - dependency-name: rq
    versions:
    - 1.7.0
  - dependency-name: faker
    versions:
    - 6.0.0
    - 6.1.1
    - 6.4.1
    - 6.5.0
    - 6.6.0
  - dependency-name: stripe
    versions:
    - 2.55.1
    - 2.55.2
  - dependency-name: pytz
    versions:
    - "2020.5"
