version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.9
      - image: redis:5
    working_directory: ~/clean-architecture/auctioning_platform
    executor: python/default
    steps:
      - checkout:
          path: ~/clean-architecture
      - restore_cache:
          keys:
          - pip-{{ checksum "requirements.txt" }}
      - run: make dev
      - save_cache:
          key: pip-{{ checksum "requirements.txt" }}
          paths:
          - /home/circleci/.local/lib/
      - run: python -m flake8 ./
      - run: python -m black ./ -l 120 --check
      - run: python -m isort --check-only ./
      - run: ./run_mypy.sh
      - run: ./run_pylint.sh
      - run:
          command: python -m pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
