version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working_directory: ~/clean-architecture/auctioning_platform
    executor: python/default
    steps:
      - checkout:
          path: ~/clean-architecture
      - restore_cache:
          keys:
          - pip-{{ checksum "requirements.txt"  }}-{{ checksum "requirements-dev.txt" }}
      - run: make dev
      - save_cache:
          key: pip-{{ checksum "requirements.txt"  }}-{{ checksum "requirements-dev.txt" }}
          paths:
          - /home/circleci/.local/lib/
      - run:
          command: python -m pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
