# Generated by Django 2.0.5 on 2018-11-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions_infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='initial_price',
            new_name='starting_price',
        ),
    ]
