# Generated by Django 2.0.5 on 2018-11-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions_infrastructure', '0004_paymenthistoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistoryentry',
            name='charge_uuid',
            field=models.UUIDField(default='627a09ec-20b4-4b6e-891f-2fc8439f7693'),
            preserve_default=False,
        ),
    ]
