# Generated by Django 2.0.5 on 2018-11-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions_infrastructure', '0005_paymenthistoryentry_charge_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistoryentry',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
