# Generated by Django 2.0.5 on 2018-11-28 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions_infrastructure', '0006_paymenthistoryentry_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='ends_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 15, 14, 21, 368490, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
